# Generated by Django 5.2 on 2025-05-07 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pow_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='Pwd',
            field=models.CharField(default='NA', max_length=255, null=True),
        ),
    ]
