# Generated by Django 5.2 on 2025-05-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pow_app', '0002_users_pwd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='District',
        ),
        migrations.AddField(
            model_name='users',
            name='State',
            field=models.CharField(choices=[('Punjab', 'Punjab'), ('Haryana', 'Haryana'), ('Rajasthan', 'Rajasthan'), ('Delhi', 'Delhi'), ('UP', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('HP', 'Himachal Pradesh'), ('J&K', 'Jammu & Kashmir'), ('Chandigarh', 'Chandigarh'), ('Chhattisgarh', 'Chhattisgarh'), ('Gujarat', 'Gujarat'), ('MP', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Goa', 'Goa'), ('DNH', 'Dadra and Nagar Haveli'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Telangana', 'Telangana'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Tamil Nadu', 'Tamil Nadu'), ('Pondy', 'Puducherry'), ('Bihar', 'Bihar'), ('Jharkhand', 'Jharkhand'), ('Odisha', 'Odisha'), ('West Bengal', 'West Bengal'), ('Sikkim', 'Sikkim'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Tripura', 'Tripura')], max_length=20, null=True),
        ),
    ]
