# Generated by Django 5.2 on 2025-05-30 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pow_app', '0003_remove_users_district_users_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='Household_ID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
