# Generated by Django 5.2 on 2025-05-30 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pow_app', '0004_users_household_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Household_ID',
            field=models.CharField(blank=True, null=True),
        ),
    ]
