# Generated by Django 5.2 on 2025-05-30 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pow_app', '0005_alter_users_household_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Household_ID',
            field=models.CharField(default='NA', max_length=255, null=True),
        ),
    ]
