# Generated by Django 5.2 on 2025-05-30 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pow_app', '0006_alter_users_household_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Household_ID',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
